#!/bin/sh

prepare_disk() {
    lsblk
    read -p "drive (/dev/disk): " DRIVE
    echo "--- PREPARING DISK -"
    parted --script $DRIVE \
        mklabel gpt \
	mkpart primary ext4 512MiB 100% \
	mkpart EFI fat32 1MiB 512MiB \
	set 2 esp on
    cryptsetup luksFormat "$DRIVE"1 --label arch_os
    cryptsetup luksOpen "$DRIVE"1 h31s
    mkfs.ext4 -O "^has_journal" /dev/mapper/h31s
    mkfs.fat -F 32 "$DRIVE"2
    mkdir -p /mnt
    mount /dev/mapper/h31s /mnt
    mkdir -p /mnt/boot
    mount "$DRIVE"2 /mnt/boot
    echo "--- DISK READY -"
}

chroot() {
    cp $0 /mnt/arch-install
    chmod 777 /mnt/arch-install
    arch-chroot /mnt ./arch-install chroot
}
    
configuracion() {
    ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
    hwclock --systohc
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    echo "KEYMAP=us" > /etc/vconsole.conf
    echo "lemon" > /etc/hostname
    cat > /etc/hosts <<EOF
127.0.0.1 localhost
::1       localhost
EOF
    systemctl enable NetworkManager
    grep -q "^Color" /etc/pacman.conf || sed -i "s/^#Color$/Color/" /etc/pacman.conf
    grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
}

usb_tweaks() {
    sed -i 's/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev block keyboard autodetect modconf encrypt filesystems fsck)/g' /etc/mkinitcpio.conf
    mkinitcpio -p linux
    sed -i 's/#Storage=auto/Storage=volatile/g' /etc/systemd/journald.conf
    sed -i 's/#SystemMaxUse=/SystemMaxUse=30M/g' /etc/systemd/journald.conf
}

install_paru() {
    echo "--- installing paru -"
    cd /tmp
    rm -rf /tmp/paru
    git clone https://aur.archlinux.org/paru.git
    chmod 777 paru
    cd paru
    sudo -u h31s makepkg --noconfirm -si
    cd /
}

user() {
    useradd -m -G wheel,video -s /bin/zsh h31s
    echo "------------- h31s PASSWORD -"
    passwd h31s
    sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/ %wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
}

bootloader() {
    echo "--- installing bootloader -"
    bootctl install
    cat > /boot/loader/loader.conf <<EOF
default  arch.conf
timeout  4
console-mode max
editor   no
EOF
    cat > /boot/loader/entries/arch.conf <<EOF
title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options cryptdevice=LABEL=arch_os:h31s root=/dev/mapper/h31s rw
EOF
    cat > /boot/loader/entries/arch-fallback.conf <<EOF
title   Arch Linux (fallback initramfs)
linux   /vmlinuz-linux
initrd  /initramfs-linux-fallback.img
options cryptdevice=LABEL=arch_os:h31s root=/dev/mapper/h31s rw
EOF
}

dotfiles() {
    git clone --bare https://github.com/h31sn0w/archusb-dotfiles.git /home/h31s/.cfg
    git --git-dir=/home/h31s/.cfg/ --work-tree=/home/h31s/ checkout
    git --git-dir=/home/h31s/.cfg/ --work-tree=/home/h31s/ config status.showUntrackedFiles no
}

set -e

if [ "$1" == "chroot" ]
then
    configuracion
    bootloader
    usb_tweaks
    echo "------------- ROOT PASSWORD -"
    passwd
    user
    install_paru
    dotfiles
    rm -f /mnt/arch-install
else
    prepare_disk
    pacstrap /mnt linux linux-firmware base base-devel vim networkmanager git zsh man-db
    genfstab -U /mnt >> /mnt/etc/fstab
    chroot
fi
