#!/bin/sh

config() {
    lsblk
    read -p "drive (/dev/disk): " DRIVE
    HOSTNAME='lemon'
    USER='h31s'
    TIMEZONE='Europe/Madrid'
    KEYMAP='us'
}

prepare_disk() {
    echo "--- PREPARING DISK -"
    parted --script $DRIVE \
        mklabel gpt \
	mkpart primary ext4 512MiB 100% \
	mkpart EFI fat32 1MiB 512MiB \
	set 2 esp on
    cryptsetup luksFormat "$DRIVE"1 --label arch_os
    cryptsetup luksOpen "$DRIVE"1 h31s
    mkfs.ext4 -O "^has_journal" /dev/mapper/h31s
    mkfs.fat -F 32 "$DRIVE"2
    mkdir -p /mnt
    mount /dev/mapper/h31s /mnt
    mkdir -p /mnt/boot
    mount "$DRIVE"2 /mnt/boot
    echo "--- DISK READY -"
}

chroot() {
    cp $0 /mnt/arch-install
    chmod 777 /mnt/arch-install
    arch-chroot /mnt ./arch-install chroot
}
    
configuracion() {
    ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
    hwclock --systohc
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    echo "KEYMAP=us" > /etc/vconsole.conf
    echo "$HOSTNAME" > /etc/hostname
    cat > /etc/hosts <<EOF
127.0.0.1 localhost
::1       localhost
EOF
    systemctl enable NetworkManager
    grep -q "^Color" /etc/pacman.conf || sed -i "s/^#Color$/Color/" /etc/pacman.conf
    grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
}

usb_tweaks() {
    sed -i 's/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev block keyboard autodetect modconf filesystems fsck)/g' /etc/mkinitcpio.conf
    mkinitcpio -p linux
    sed -i 's/#Storage=auto/Storage=volatile/g' /etc/systemd/journald.conf
    sed -i 's/#SystemMaxUse=/SystemMaxUse=30M/g' /etc/systemd/journald.conf
}

install_paru() {
    echo "--- installing paru -"
    cd /tmp
    rm -rf /tmp/paru
    git clone https://aur.archlinux.org/paru.git
    chmod 777 paru
    cd paru
    sudo -u $USER makepkg --noconfirm -si
    cd /
}

user() {
    useradd -m -G wheel -s /bin/zsh $USER
    echo "------------- $USER PASSWORD -"
    passwd $USER
    sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/ %wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
}

bootloader() {
    echo "--- installing bootloader -"
    bootctl install
    cat > /boot/loader/loader.conf <<EOF
default  arch.conf
timeout  4
console-mode max
editor   no
EOF
    cat > /boot/loader/entries/arch.conf <<EOF
title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root="LABEL=arch_os" rw
EOF
    cat > /boot/loader/entries/arch-fallback.conf <<EOF
title   Arch Linux (fallback initramfs)
linux   /vmlinuz-linux
initrd  /initramfs-linux-fallback.img
options root="LABEL=arch_os" rw
EOF
}

sway() {
    echo "--- installing sway stuff -"
    pacman --noconfirm -S sway swaylock swayidle imv mpv mako swappy grim slurp
    sudo -u $USER paru --no-confirm greetd-tuigreet foot dmenu-wayland-git autotiling
}

set -e

if [ "$1" == "chroot" ]
then
    configuracion
    bootloader
    usb_tweaks
    echo "------------- ROOT PASSWORD -"
    passwd
    user
    install_paru
    sway
    rm -f /mnt/arch-install
else
    config
    prepare_disk
    pacstrap /mnt linux linux-firmware base base-devel vim networkmanager git zsh pipewire pipewire-alsa pipewire-pulse
    genfstab -U /mnt >> /mnt/etc/fstab
    chroot
fi
